# Multi-threshold Neuron - Part 1

In this first notebook I will try to formulate the simple maths and pseudocode to implement the concept of a new type of neuron proposed last year in July.

I have not check if this idea already exist in a code implementation. I would imagine it does in some form but I prefer to have a nice time without peeking into the answer :).

![model proposal comparison](images/model_proposal.png)

## Concepts

There are some main concepts in the Deep Learning domain that you should be familiar with before procedding. If you are familiar with them skip this part.

**Artificial neuron**

<img align='left'src="images/neuron_comparison.png" width="300px">
A mathematical representation of a biological neuron. They are the corner stone of artificial neural networks and Deep Learning in general. The idea is that the artificial neuron receives input signals from other connected artificial neurons and via a non-linear transmission function emits a signal itself. This transmission function is commonly known as the activation function.

**Activation function**

<img align='left'src="images/relu.png" width="300px">
The current understanding of a neuron is that it will transmit some signal only if the sum from incoming signals from other neurons exceeds a threshold. For an artificial neuron this is done via an activation function. There are many of them, and they also add non-linearity to the artificial neural network. There are many [activation functions](https://en.wikipedia.org/wiki/Activation_function) but the Rectified linear unit (ReLu) is recently one of the most broadly used in the Deep Learning community, and it's the one I will use in this notebook. The strict mathematical definition of the function is:

$$R(z) = max(0, z) =
     \begin{cases}
       0 &\quad\text{for } z\leq0 \\
       z &\quad\text{for } z > 0
     \end{cases}$$
     
You can check it out in the the official [Tensorflow code](https://github.com/tensorflow/tensorflow/blob/48be6a56d5c49d019ca049f8c48b2df597594343/tensorflow/compiler/tf2xla/kernels/relu_op.cc#L37) or in the [Tensorflow playground](https://github.com/tensorflow/playground/blob/718a6c8f2f876d5450b105e269534ae58e70223d/nn.ts#L120). (as you can notice the derivative is not continuous on $z=0$, this actually caused a bit of hessitation to adopt the activation function due to the fear of "braking" back-propagation which is based on derivating all elements of a neural network. So actually the derivative has to be written explicitly check tensorflow source code.)


## Scientific background

S. Sardi *et al.* publish in July last year an experimental work in [Nature scientific reports](https://www.nature.com/srep/) which contradicts a century old assumption about how neurons work. The work was a combined effort between the Physics, Life Sciences and Neuroscience departments of Bar-Ilan University in Tel Aviv.

![article_title](images/article.png)

The proposed neurons models contain a transmission function which in Deep Learning we refer to as [activation functions](https://en.wikipedia.org/wiki/Activation_function). The authors specifically refer to this function as the neuronal equations.  Their study put to the test three different conceptual neuron models, which I will name: centralized-single-threshold-neuron, centralized-multi-threshold-neuron and decentralized-multi-threshold-neuron.

**Centralized-Single-Threshold-Neuron**

This is the current adopted computational description of neurons ([artificial neurons](https://en.wikipedia.org/wiki/Artificial_neuron)), and the corner stone of Deep Learning. "A neuron consists of a unique centralized excitable mechanism". The signal reaching the neuron consists of a linear sum of the incoming signals from all the dendrites connected to the neuron. If this sum reaches a threshold, a spike signal is propagated through the axiom to the other connected neurons.

The neuronal equation of this model is:

$$I = \Theta\Big(\sum_{i=1}^NW_i\cdot I_i - t\Big)$$

where
- $i$: identifies any connected neuron
- $N$: total number of connected neurons
- $W_i$: is the weight (strenght) associated to the connection with neuron $i$
- $I_i$: is the signal comming out of neuron $i$
- $t$: is the centralized single neuron threshold 
- $\Theta$: is the heavyside step function
- $I$: signal output from the neuron




**Centralized-multi-threshold-neuron**

As for the Centralized-Single-Threshold-Neuron there is a centralized threshold applied by an activation function. The difference is that this model assumess non-linearity signal transmission in each dendrite and a threshold unit for each dendrite. This model is the most complex of the three and its neuronal equation can be written as:

$$I=\Theta(s - t)$$
$$s = \sum_{i=1}^Nf_i(W_i\cdot I_i)\cdot\Theta(W_i\cdot I_i - t_i)$$

where
- $i$: identifies any connected neuron
- $N$: total number of connected neurons
- $W_i$: is the weight (strenght) associated to the connection with neuron $i$
- $I_i$: is the signal comming out of neuron $i$
- $t_i$: is the threshold value for each neuron $i$
- $\Theta$: is the heavyside step function
- $f_i$: non-linear transfer function for connection $i$
- $t$: is the centralized single neuron threshold 
- $I$: signal output from the neuron

**Decentralized-Multi-Threshold-Neuron**

In this model the centralized threshold applied by the centralized activation function is removed. The neuron can be independently excited by any singal coming from a dendrite given that this signal is above a threshold. In escence this model describes a multi-threshold neuron. The mathematical representation is much simpler than the centralized-multi-threshold-neuron and it reads:

$$I=\sum_{i=1}^N\Theta(W_i\cdot I_i - t_i)$$
(here the authors write an OR, so this equation is correct if they meant the logical OR and not XOR.)

where
- $i$: identifies any connected neuron
- $N$: total number of connected neurons
- $W_i$: is the weight (strenght) associated to the connection with neuron $i$
- $I_i$: is the signal comming out of neuron $i$
- $t_i$: is the threshold value for each neuron $i$
- $\Theta$: is the heavyside step function
- $I$: signal output from the neuron

**Study conclusion**

Based on their experiments the authors conclude that the **Decentralized-Multi-Threshold-Neuron** model explains the data. The authors mention that the main reason for adopting the Centralized-Single-Threshold-Neuron as the main model, is that technology did not allow for direct excitation of single neurons, which other model experiments require. Moreover they state that these results could have been discovered using tehcnology that existed since the 1980s.

## The challenge

My idea is to take the Decentralized-Multi-Threshold-Neuron model and try to write an Deep Learning implementation, that is a neural network which will consist of multi-threshold neurons. From the current tools available for Deep Learning Tensorflow is quite flexible and allows for writting user defined implementations, if for some reason the flexibility is not there I will have to write the neural network myself (I hope not, even though I will recommend doing this at least once to really understand how the pieces of a neural network fit togethter.).

### Approximations

I am a theoretical physicist and as such it's impossible for me not to look for the [spherical cow](https://en.wikipedia.org/wiki/Spherical_cow).

**Single threshold value**

The multi-threshold neuron model contains different threshold parameter values ($t_i$). Mathematically a threshold has the same effect if we take it as a constant and instead the input signal is moved up or down by the connecting weights parameters. Hence, the neuronal equation becomes:

$$I=\sum_{i=1}^N\Theta(W_i\cdot I_i - t)$$

(this is also happening in the current neural network implementations, since in reality there is no reason for different neurons to have the same threshold, nevertheless commonly a single activation function is used on all neurons.)

**ReLu activation function**

The authors mention the neuronal equation, here I will take a step forward and define what in neuroscience is a transmission function. I basically will replace the heavisyde step function ($\Theta$) with threshold $t$ by a Rectified Linear Unit ($\mathcal{R}$). I write the transmission function as:

$$I=\sum_{i=1}^N\mathcal{R}(W_i\cdot I_i)$$

In general any activation function could replace the heavyside step function.

**Zero bias**

Notice that the proposed model equation contains no bias terms. For simplicity I will keep all bias equal to zero. Hopefully as a second iteration of the code architecture I will be able to add them easily.

### Backpropagation

In order for my neural network to be trained I will probably need backpropagation at some point, this means that the derivative of whatever function I introduce is necessary. Lucky for me I'm not changing the activation function equation itself, so I just use the already derivative of the ReLu function in Tensorflow:

$$\frac{d}{dz}\mathcal{R}(z)=
     \begin{cases}
       0 &\quad\text{for } z\leq0 \\
       1 &\quad\text{for } z > 0
     \end{cases}$$
     
You can check it out in the the official [Tensorflow code](https://github.com/tensorflow/tensorflow/blob/48be6a56d5c49d019ca049f8c48b2df597594343/tensorflow/compiler/tf2xla/kernels/relu_op.cc#L63) or in the [Tensorflow playground](https://github.com/tensorflow/playground/blob/718a6c8f2f876d5450b105e269534ae58e70223d/nn.ts#L121).

### Tensor multiplication

What I'm really changing is the architecture of the neural network as seen in Figure 0,  the activation function is no longer applied on the sum of all the inputs from the connected neurons, but instead on each input arriving from a connected neuron. In a simple description the sum over the arriving signal is going from inside the activation function to outside of it:


$$\mathcal{R}\Big(\sum_{i=1}^NW_i\cdot I_i\Big) \rightarrow \sum_{i=1}^N\mathcal{R}(W_i\cdot I_i)$$

Do you see the implementation problem described by the equation above?

In the current model (left equation) the input to the activation function $\sum_iW_i\cdot I_i$ is exactly the dot product between vectors $(W_1, W_2,\dots,W_N)$ and $(I_1, I_2,\dots,I_N)$ and it's this fact which allows fast computation of input signals for many neurons via matrix multiplication. In the fully connected layer for example, the input signal for $j$ neurons comming from connected neurons $i$ is $\sum_iW_{ji}\cdot I_i$, which means we can calculate the input signal for all $j$ neurons with one simple matrix multiplication $W \cdot I$ (given that $I$ is written as a $N\times1$ matrix).

In the new model this is no longer possible. I think this will be the biggest challenge, but AFAIK Tensorflow should provide enough flexibility to write this architecture. The idea is to keep things in the tensorflow world as all the functions in the package can be added to calculations and gradients will be automatically available for backpropagation.

It is also interesting to think about if the fact that we can do fast matrix multiplications lead us to prefer the current central-threshold model, like the modified Maslow's hammer saying goes "if all you have is a hammer, everything looks like a nail".

## Mathematical Implications

## Pseudo-code

Tensorflow contains two built-in realted `ReLu` functions:

- `relu_layer`
- `relu`

The `relu_layer` function already assumes an architecture with centralized-threshold neurons $\mathcal{R}\Big(\sum_{i=1}^NW_i\cdot I_i\Big)$. The `relu` function on the other hand can operate on each entry of an array.

**example**

Suppose we have the following weight matrix connecting two neuron layers, the first layer has 3 neurons the second with 2:

$$W=
\begin{bmatrix}
    3 & -4 \\
    -2& 2\\
    0& 4
\end{bmatrix}
$$

and that the output signal from the neurons in the first layer are:

$$I_0=
\begin{bmatrix}
    2 & 5 & 1  
\end{bmatrix}
$$

Then in the standard centralized-threshold neuron model the output signal from the second layer is:

$$\mathcal{R}\Big(I_0\cdot W\Big) = \mathcal{R}\Big(
\begin{bmatrix}
    2 & 5 & 1  
\end{bmatrix}
\cdot
\begin{bmatrix}
    3 & -4 \\
    -2& 2\\
    0& 4
\end{bmatrix}
\Big)
=
\mathcal{R}\Big(
\begin{bmatrix}
    -4 & 6 
\end{bmatrix}
\Big)
=
\begin{bmatrix}
    \mathcal{R}(-4) & \mathcal{R}(6)
\end{bmatrix}
\Big)
=
\begin{bmatrix}
    0 & 6 
\end{bmatrix}
$$

In the case of the multi-threshold neuron model proposed we have an output like

$$\mathcal{R}\Big(
\begin{bmatrix}
    2 & 5 & 1  
\end{bmatrix}
\bigcirc
\begin{bmatrix}
    3 & -4 \\
    -2& 2\\
    0& 4
\end{bmatrix}
\Big)
=
\begin{bmatrix}
    \mathcal{R}(6) + \mathcal{R}(-10) + \mathcal{R}(0) & \mathcal{R}(-8) + \mathcal{R}(10) + \mathcal{R}(4) 
\end{bmatrix}
=
\begin{bmatrix}
    6 & 14 
\end{bmatrix}
$$

As the example shows, a fundamental difference is that in the multi-thresholh case if any term (neuron output signal times weight) is positive then the output will be different than zero. This will of course greatly reduce the sparsity of the neurons firing throughout the network in comparison with the conventional centralized-threshold model. I am ignorant about what are all the implications of this. I expect that it will be more difficult for individual neurons (or parts of the network) to address a specific feature, therefore reducing overfitting. Something similar is achieved in current Deep Neural Networks using the [Drop Out technique](https://en.wikipedia.org/wiki/Convolutional_neural_network#Dropout).

**Initial tensorflow implementation**
```python
import tensorflow as tf
sess = tf.Session()
```

In [337]:
import tensorflow as tf
sess = tf.Session()

**Centralized-threshold Neuron**
```python
w = tf.constant([[3, -4], [-2, 2], [0, 4]])
I_0 = tf.constant([[2, 5, 1]])
I_1 = tf.nn.relu(tf.matmul(I_0, w))
I_1.eval(session=sess)
>>> array([[0, 6]], dtype=int32)
```

In [338]:
w = tf.constant([[3, -4], [-2, 2], [0, 4]])
I_0 = tf.constant([[2, 5, 1]])
I_1 = tf.nn.relu(tf.matmul(I_0, w))
I_1.eval(session=sess)

array([[0, 6]], dtype=int32)

**Multi-threshold Neuron**

```python
w = tf.constant([[3, -2, 0], [-4, 2, 4]])
I_0 = tf.constant([2, 5, 1])
I_1 = tf.reduce_sum(tf.nn.relu(tf.multiply(I_0, w)), axis=1)
I_1.eval(session=sess)
>>> array([ 6, 14], dtype=int32)
```

In [339]:
w = tf.constant([[3, -2, 0], [-4, 2, 4]])
I_0 = tf.constant([2, 5, 1])
I_1 = tf.reduce_sum(tf.nn.relu(tf.multiply(I_0, w)), axis=1)
I_1.eval(session=sess)

array([ 6, 14], dtype=int32)

## 2 hidden layer multi-threshold neuron network

In [340]:
def multi_treshold_layer(input_values, weights, activation=tf.nn.relu):
    return tf.reduce_sum(activation(tf.multiply(input_values, weights)), axis=1)

In [341]:
from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("/tmp/data/", one_hot=True)

Extracting /tmp/data/train-images-idx3-ubyte.gz
Extracting /tmp/data/train-labels-idx1-ubyte.gz
Extracting /tmp/data/t10k-images-idx3-ubyte.gz
Extracting /tmp/data/t10k-labels-idx1-ubyte.gz


In [342]:
# Parameters
learning_rate = 0.001
n_epochs = 5

# Network Parameters
hlayers_sizes = [251, 87]
n_input = 784 # MNIST data input (img shape: 28*28)
n_classes = 10 # MNIST total classes (0-9 digits)

tf.reset_default_graph()

# Construct model
I_0 = tf.placeholder("float", shape=(n_input,))
W_01 = tf.Variable(tf.random_normal((hlayers_sizes[0], n_input)))
I_1 = multi_treshold_layer(I_0, W_01)
W_12 = tf.Variable(tf.random_normal((hlayers_sizes[1], hlayers_sizes[0])))
I_2 = multi_treshold_layer(I_1, W_12)
W_23 = tf.Variable(tf.random_normal((n_classes, hlayers_sizes[1])))
output = multi_treshold_layer(I_2, W_23)

# label data for training
target = tf.placeholder("float", shape=(n_classes,))

In [352]:
# Define loss and optimizer
loss = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=output, labels=target))
correct_prediction = tf.equal(tf.argmax(output), tf.argmax(target))
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

# Initializing the variables
init = tf.global_variables_initializer()

In [365]:
n_observations = mnist.train.num_examples // 50

print('# Examples in Epoch:', n_observations)
print('# Epochs:', n_epochs)

losses = []
accuracies = []

with tf.Session() as sess:
    sess.run(init)

    # Training cycle
    for epoch in range(n_epochs):
        avg_loss = 0
        acc = 0
        # Loop over all examples
        for i in range(n_observations):
            x, y = mnist.train.next_batch(1)
            # Run optimization op (backprop) and cost op (to get loss value)
            _, l, c = sess.run([optimizer, loss, correct_prediction], feed_dict={I_0: x[0], target: y[0]})
            # Compute average loss
            avg_loss += l
            acc += c
        # Display logs per epoch step
        avg_loss /= n_observations
        acc /= n_observations
        print(f'Epoch: {epoch + 1}\t Avg Loss: {avg_loss:.3f}\t Accuracy: {acc:.3f}')
        losses.append(avg_loss), accuracies.append(acc)
    print("Optimization Finished!")
    
    # Test metrics
    accuracy = 0
    for i in range(n_observations):
        x_test, y_test = mnist.test.next_batch(1)
        accuracy += correct_prediction.eval({I_0: x_test[0], target: y_test[0]})
    accuracy /= n_observations
    print(f"Accuracy on test set: {accuracy:.3f}")

# Examples in Epoch: 1100
# Epochs: 5
Epoch: 1	 Avg Loss: 3324.479	 Accuracy: 0.279
Epoch: 2	 Avg Loss: 232.377	 Accuracy: 0.499
Epoch: 3	 Avg Loss: 201.601	 Accuracy: 0.582
Epoch: 4	 Avg Loss: 212.326	 Accuracy: 0.613
Epoch: 5	 Avg Loss: 178.886	 Accuracy: 0.655
Optimization Finished!
Accuracy on test set: 0.611
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]
[53139.24  53968.94  53462.086 52916.42  53147.555 53405.484 53408.535
 53601.047 53289.805 52680.504]
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
[119136.14  118523.28  119029.39  118085.945 118899.18  119853.78
 120792.37  118650.3   119084.57  117448.17 ]
